### ISSUE TITLE
Todo List from 7/28 Meeting 

### ISSUE THREAD

**Issue by albertkun** [LACMTA/gopass-lookup#13]
- [ ] add the public schools from the california edu list
- [ ] come up with form for schools that aren't participating 
- [x] add districts to school names
- [ ] incorporate private schools when they arrive
- [ ] maybe add fuzzy logic for school selections
      - this library might be helpful https://github.com/nol13/fuzzball.js/

Data issues are being tracked in #14

**Comment by albertkun** [comment]
Issues identified:

1. One school has multiple records, only the contact information changes
2. School names are different than in the California data set, for example, `109th Street Elementary` is `One Hundred Nineth Street Elementary`, this is also the official spelling: https://109street-lausd-ca.schoolloop.com/
3. Differences in address formatting, `south` vs. `s` and `Mc Kinley` vs. `McKinley`, the `McKinley` is also the official spelling on the website.
4. Typos in the California data set....:
`One Hundred Seventh Street Mag,47 E. 107Th St.,Los Angeles,CA,90003` should be `147 E. 107th St.`

**Comment by matikin9** [comment]
All good!
