### ISSUE TITLE
Google Analytics Tracking & Reporting

### ISSUE THREAD

**Issue by matikin9** [LACMTA/gopass-lookup#8]
Data to track for reporting:

- [ ] Percentage of visitors who search for a school after reaching the landing page.
- [ ] Counts of how many times each school has been searched searched, with this additional data for filtering:
  - [ ] Already a GoPass participant or not?
  - [ ] School coordinates for map visualization
- [ ] Maybe a CTA after a school has been found?
- [ ] From Devon/TAP:
  - [ ] Changes in schools participating
  - [ ] Numbers of cards distributed to each school

Technical requirements:

- [ ] Set up GA4 account and tracking
- [ ] Set up GTM container and event tagging
- [ ] Set up automated reports (email or Slack channel?)
- [ ] Set up a location where hits per school will be updated - GA? Google Form/Sheet?
  - [ ] Connect a map to pull from this data source
  - [ ] Create a heatmap of the data.
